name: CI (Linux)

on: [push]

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Generate Project Files
      run: premake5 gmake2

    - name: Build Project
      run: make -j
