name: CI (Linux)

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ master ]
    paths-ignore: [ .github/**, resources/**, .clang-format, .editorconfig, .gitignore, README.md, LICENSE ]

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Generate project files
      run: premake5 gmake2

    - name: Build project
      run: make -j
