name: CI (macOS)

on: [push]

jobs:
  build:
    runs-on: [self-hosted, macOS]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Generate Project Files
      run: premake5 xcode4

    - name: Build Project
      run: xcodebuild build -workspace "Geno.xcworkspace" -scheme "Geno" -configuration Release | xcpretty
