name: CI (Windows)

on: [push]

jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Generate Project Files
      run: premake5.exe vs2019

    - name: Build Project
      run: C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/BuildTools/MSBuild/Current/Bin/MSBuild.exe -property:Configuration=Release -maxCpuCount -verbosity:minimal -noLogo Geno.sln
