name: CI (Windows)

on:
  pull_request:
    branches: [ master ]
    types: [ opened, closed, reopened, synchronize ]
  push:
    branches-ignore: [ master ]
    paths-ignore: [ .github/**, resources/**, .clang-format, .editorconfig, .gitignore, README.md, LICENSE ]

jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Generate project files
      run: premake5.exe vs2019

    - name: Build project
      run: C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/BuildTools/MSBuild/Current/Bin/MSBuild.exe -property:Configuration=Release -maxCpuCount -verbosity:minimal -noLogo Geno.sln
